# -*- coding: utf-8 -*-
"""Task 5: Interactive Business Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oqa51TAD8h-zFldJEw-2K848mEYDpdPj
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

# Load dataset
df = pd.read_csv("Global_Superstore.csv")

# Convert numeric columns and drop missing values
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')

# Keep only rows with important columns
df = df.dropna(subset=['Sales', 'Profit', 'Customer Name', 'Region', 'Category', 'Sub-Category'])

# Load dataset
df = pd.read_csv("Global_Superstore.csv")

# Convert numeric columns and drop missing values
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')

# Keep only rows with important columns
df = df.dropna(subset=['Sales', 'Profit', 'Customer Name', 'Region', 'Category', 'Sub-Category'])

# Page configuration
st.set_page_config(page_title="Global Superstore Dashboard", layout="wide")
st.title("📊 Global Superstore Interactive Dashboard")

# Sidebar filters
st.sidebar.header("Filters")
region_filter = st.sidebar.multiselect("Select Region(s):", options=df['Region'].unique(), default=df['Region'].unique())
category_filter = st.sidebar.multiselect("Select Category(s):", options=df['Category'].unique(), default=df['Category'].unique())
subcat_filter = st.sidebar.multiselect("Select Sub-Category(s):", options=df['Sub-Category'].unique(), default=df['Sub-Category'].unique())

# Apply filters
filtered_df = df[(df['Region'].isin(region_filter)) &
                 (df['Category'].isin(category_filter)) &
                 (df['Sub-Category'].isin(subcat_filter))]

# Calculate KPIs
total_sales = filtered_df['Sales'].sum()
total_profit = filtered_df['Profit'].sum()
top_customers = filtered_df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(5)

# Display KPIs
col1, col2 = st.columns(2)
col1.metric("💰 Total Sales", f"${total_sales:,.0f}")
col2.metric("📈 Total Profit", f"${total_profit:,.0f}")

# Display Top 5 Customers
st.subheader("🏆 Top 5 Customers by Sales")
st.table(top_customers.reset_index().rename(columns={'Sales':'Total Sales'}))

st.subheader("Profit by Region")
profit_region = filtered_df.groupby('Region')['Profit'].sum().reset_index()
fig2 = px.pie(profit_region, names='Region', values='Profit', hole=0.4)
st.plotly_chart(fig2, use_container_width=True)

st.subheader("Sales Trend by Sub-Category")
sales_subcat = filtered_df.groupby('Sub-Category')['Sales'].sum().reset_index()
fig3 = px.line(sales_subcat, x='Sub-Category', y='Sales', markers=True)
st.plotly_chart(fig3, use_container_width=True)